### ISSUE TITLE
Redundant unhandledrejection events

### ISSUE THREAD

**Issue by SleepWalker** [es-shims/Promise.prototype.finally#10]
Hi,

if you'll write something like this:

```js
Promise.reject('reject')
  .finally(() => console.warn('finally'))
  .catch(() => console.warn('catch'));
```

You'll get the following output:

```
finally
catch
Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: undefined}
Uncaught (in promise) reject
```

The last `Uncaught (in promise) reject` looks to be odd here, because the promise was properly handled.

Here is another example, where the promise rejection was not handled:

```js
Promise.reject('reject')
  .finally(() => console.warn('finally'));
```

and the output is:

```
finally
Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: "reject"}
Uncaught (in promise) reject
Uncaught (in promise) reject
```

The promise rejection was not handled at all and we got two `unhandledrejection` instead of one.

Each new `finally` in promise chain will produce one extra `unhandledrejection` event. This will result in four events triggered:

```js
Promise.reject('reject')
  .finally(() => console.warn('finally'))
  .finally(() => console.warn('finally'))
  .finally(() => console.warn('finally'));
```

Does this correct behaviour? If yes, then how should I handle those extra rejections?

**Comment by ljharb** [comment]
Interesting - I would definitely expect that the `.catch` example would not fire any unhandled rejection errors; and that your chain of `.finally`s would produce only one.

**Comment by ljharb** [comment]
In `node --harmony-promise-finally`, I only see the expected unhandled rejection errors.

I definitely can reproduce this with this package in `node`.

**Comment by SleepWalker** [comment]
Wow. Thanks a lot for the super fast fix!
