### ISSUE TITLE
Angular-CLI Usage?

### ISSUE THREAD

**Issue by alsoicode** [es-shims/Promise.prototype.finally#14]
Where do I need to call `shim()` ?

I'm assuming it needs to go in `main.ts`:

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { shim } from 'promise.prototype.finally';

shim();

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));
```

however, the TypeScript compiler complains about not finding the 'finally' property in implementations: `error TS2339: Property 'finally' does not exist on type 'Promise<void>'`

What am I doing wrong?

**Comment by ljharb** [comment]
Your code is correct.

However, this shim is for JavaScript, and as such, it doesn't shim the TypeScript compiler's `Promise` type. You'll have to file an issue on TypeScript itself for that.

**Comment by alsoicode** [comment]
Thanks @ljharb I added: https://www.npmjs.com/package/@types/promise.prototype.finally and we're all set.
