### ISSUE TITLE
Not working in firefox

### ISSUE THREAD

**Issue by mtdx** [es-shims/Promise.prototype.finally#15]
Hello, I have this error `.fetch(...).then(...).finally is not a function`, in firefox (latest version) only. If I remove all `.finally(() => { });` functions for the app it works, also if I run it with webpack dev server works, but in production or with webpack dev server with the `-p` flag it doesn't work anymore. 

I'm using 2.0.1 version, but I tried the latest 3.0.1 too and same, didn't do nothing. Any ideas?

**Comment by ljharb** [comment]
Can you elaborate on how you're "using" this shim? Specifically, the code that includes it?

**Comment by davidrobbo** [comment]
@mtdx I was having the same issue, but recommendation in #7 sorted it for me.

```
import 'es6-shim'
import 'promise.prototype.finally'
import shim from 'promise.prototype.finally/shim'
shim()
```

**Comment by ljharb** [comment]
@davidrobbo fwiw `import 'promise.prototype.finally'` does absolutely nothing, so you can just remove that line :-)
