### ISSUE TITLE
Add browser file

### ISSUE THREAD

**Issue by nojaf** [es-shims/Promise.prototype.finally#17]
It be nice if the npm package ships with a single file that needs to be included to polyfill `finally` globally in the browser.

**Comment by ljharb** [comment]
There's no need for this; you always need a bundler for modern web dev, so `require('promise.prototype.finally/auto')` should be sufficient.

You can potentially use https://wzrd.in/standalone/promise.prototype.finally@latest as well.

**Comment by nmoinvaz** [comment]
```
npm install -g browserify
npm install
browserify auto.js > promise.prototype.finally.js
```

**Comment by ljharb** [comment]
@nmoinvaz the "old version" you're referring to is wildly incorrect, and predates the actual spec. Note as well that this polyfill dedupes nicely with most of the other ones in https://npmjs.com/airbnb-browser-shims, so the cost isn't accurate when measured standalone.
