### ISSUE TITLE
Loading the polyfill on Chrome 67 will raise a warning

### ISSUE THREAD

**Issue by sylvhama** [es-shims/Promise.prototype.finally#18]
When using this code in my project:
```
import promiseFinally from 'promise.prototype.finally';
promiseFinally.shim();
```
I will see this warning in Chrome 67.0.3396.87 console:
`
index.js:51 [Deprecation] Application Cache is deprecated in non-secure contexts, and will be restricted to secure contexts in M69, around September 2018. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.
`

**Comment by ljharb** [comment]
I'm not sure how that's possible; the shim isn't using appcache in any way. However, that warning only pops up on HTTP pages - your project (every project) should be on HTTPS regardless.

What's on line 51 of index.js?

**Comment by sylvhama** [comment]
I am using https://github.com/facebook/create-react-app which uses Webpack under the hood. 
The details of the watning are:
```
(anonymous) @ index.js:51
./node_modules/object-keys/index.js @ index.js:63
__webpack_require__ @ bootstrap de4b3a93674cc1e1a28b:707
fn @ bootstrap de4b3a93674cc1e1a28b:112
./node_modules/define-properties/index.js @ index.js:3
__webpack_require__ @ bootstrap de4b3a93674cc1e1a28b:707
fn @ bootstrap de4b3a93674cc1e1a28b:112
./node_modules/promise.prototype.finally/index.js @ index.js:4
__webpack_require__ @ bootstrap de4b3a93674cc1e1a28b:707
fn @ bootstrap de4b3a93674cc1e1a28b:112
./src/scripts/appInit/polyfills.js @ polyfills.js:1
__webpack_require__ @ bootstrap de4b3a93674cc1e1a28b:707
fn @ bootstrap de4b3a93674cc1e1a28b:112
./src/scripts/appInit/index.js @ index.js:1
__webpack_require__ @ bootstrap de4b3a93674cc1e1a28b:707
fn @ bootstrap de4b3a93674cc1e1a28b:112
./src/index.js @ index.css?f255:26
__webpack_require__ @ bootstrap de4b3a93674cc1e1a28b:707
fn @ bootstrap de4b3a93674cc1e1a28b:112
0 @ mixins.js:29
__webpack_require__ @ bootstrap de4b3a93674cc1e1a28b:707
(anonymous) @ bootstrap de4b3a93674cc1e1a28b:805
(anonymous) @ bootstrap de4b3a93674cc1e1a28b:805
```

I confirm that the line `import promiseFinally from 'promise.prototype.finally';` is causing this warning.

**Comment by ljharb** [comment]
How can you confirm that? The error is on line 51; you’re doing an import of it on line 51?

**Comment by ljharb** [comment]
Ohhhh i think i see the issue, it’s inside object-keys.

If you import object-keys instead of this package, do you get the same warning?

If so, please file an issue on https://github.com/ljharb/object-keys and i can address it there.

**Comment by sylvhama** [comment]
I am using [JS modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), the line 51 mentioned in the warning is from the bundle generated by [Webpack](https://webpack.js.org/guides/getting-started/). 
Anyway, if you download this project: https://codesandbox.io/s/kxp55lx90o and then do
```
npm isntall
npm start
```
You will see the warning in the console.

**Comment by sylvhama** [comment]
@ljharb you are right!
If I do `import objectKeys from 'object-keys';` it will generate the same warning:

**Comment by sylvhama** [comment]
I am closing this issue an opening a new one: https://github.com/ljharb/object-keys/issues/46
