### ISSUE TITLE
Consider removing es-abstract dependency to reduce size considerably

### ISSUE THREAD

**Issue by blikblum** [es-shims/Promise.prototype.finally#21]
Just looked at the bundle size through source-map-explorer and observed that 'es-abstract' required by  'Promise.prototype.finally' takes 43Kb of minified bundle size 13,9% of total.

This package uses few es-abstract methods and removing its reliance on it, would decrease the size considerably.

If you think is doable, i can prepare a PR.

**Comment by ljharb** [comment]
It’s not doable; es-abstract is required for correctness.

I’m not sure how you’re bundling it, nor what other polyfills/shims you’re including, but i have a host of them that all use a single es-abstract - so in practice, most of it is needed anyways.

I have work in progress on es-abstract itself to help make bundle sizes smaller already.

**Comment by blikblum** [comment]
It's the only polyfill used. I will drop 'promise.prototype.finally' usage.

Thanks for the response.

**Comment by ljharb** [comment]
Sorry to hear that; correctness is more important than bundle size ¯\\\_(ツ)_/¯

**Comment by blikblum** [comment]
> Sorry to hear that; correctness is more important than bundle size ¯\_(ツ)_/¯

Is possible to keep correctness and reduce bundle size in this case. Time allowing, i will look on it.

**Comment by ljharb** [comment]
On master:
```sh
$ npx browserify index.js | wc -c
  130424
```

After linking in and using the new architecture from es-abstract:
```sh
$ npx browserify index.js | wc -c
   28116
```

which is an *unminified* drop of 78% (127k vs 27k). I suspect this will be an easy win.

**Comment by ljharb** [comment]
v3.1.2 has been released which takes this new architecture into account. Bundle sizes should be much smaller now.

**Comment by blikblum** [comment]
Many thanks. You can see the result here: https://bundlephobia.com/result?p=promise.prototype.finally@3.1.2

It went from 33kb to 14Kb minified.
