### ISSUE TITLE
Fails on IE11

### ISSUE THREAD

**Issue by torarnek** [es-shims/Promise.prototype.finally#3]
We get 
``SCRIPT5007: Unable to get property 'configurable' of undefined or null reference``
on line
``if (Object.getOwnPropertyDescriptor && Object.getOwnPropertyDescriptor(promiseFinally, 'name').configurable)``

We are using Profile polyfill from https://github.com/zloirock/core-js

**Comment by ljharb** [comment]
whoops, thanks

**Comment by torarnek** [comment]
Thank you very much for fixing this so fast! :)

**Comment by ljharb** [comment]
Thanks for the report!
