### ISSUE TITLE
this._c is undefined

### ISSUE THREAD

**Issue by jonashaag** [es-shims/Promise.prototype.finally#5]
This might be related to #4 as it only happens with Firefox, but I couldn't figure out the root cause and I don't have a minimal example.

Setup:

```
promise = ...fetch(...)
promiseFinally(promise, () => ...)
```

Now at some point we hit

```
this._c is undefined
```

in this line: https://github.com/zloirock/core-js/blob/0bb657cfc7834d03fd68c48a1cba70f2ccab20c0/modules/es6.promise.js#L212

`this` is `window` when the error happens, which is obviously wrong. So something seems to be wrongly bound there.

I'm not even sure this is an issue with this library, but it goes away when I switch to es6-promise.

**Comment by ljharb** [comment]
That does suggest the wrong `this` value. If you stick a debugger just before that line, what's the value of `this`?

**Comment by jonashaag** [comment]
> That does suggest the wrong this value. If you stick a debugger just before that line, what's the value of this?

`window`

**Comment by ljharb** [comment]
(Sorry for the back and forth) what about if you do `new Error().stack`?

**Comment by jonashaag** [comment]
OK, I believe I figured out what's wrong here.

These are the values of `this` in the core-js promise library at different times:

```
Object { _c: Array[0], _a: undefined, _s: 0, _d: false, ... }

Object { _c: Array[0], _a: undefined, _s: 0, _d: false, ... }

Promise { <state>: "pending" }
```

Notice the last one, which is a native promise object. It seems like the wrong `then` method is selected by finally: The core-js promise one instead of the native one. So the problem seems to be that finally assumes all promise objects are always of the same kind when it statically saves the "original" `then` method here (generated finally source code excerpt):

```
	var then = bind.call(Function.call, Promise.prototype.then);
```

I'm not sure if it's just our code/setup that's stupid or if it's actually a legitimate case that finally doesn't consider.

**Comment by ljharb** [comment]
In that case, you need to load core-js *before* this shim, so that the `then` method it caches is core-js's.

**Comment by jonashaag** [comment]
> In that case, you need to load core-js before this shim, so that the then method it caches is core-js's.

That's what we're doing. I just had another look. It seems the other way round!

Doesn't work:
```
require('core-js/es6/promise')
require('promise.prototype.finally')
```

Works:
```
require('promise.prototype.finally')
require('core-js/es6/promise')
```

**Comment by ljharb** [comment]
Note that `require('promise.prototype.finally')` does not shim anything automatically, you'd need to require `/shim`, or call `.shim()`.

**Comment by jonashaag** [comment]
Yeah, I don't use the shim syntax, so that's not the problem.

**Comment by ljharb** [comment]
I see, so you're just requiring it as a bound function?

**Comment by jonashaag** [comment]
Actually, we have two places were it's required, for webpack reasons. The first place (also the first in the compiled JS) is the one I showed in which the order seems to matter. The second place is where we actually use it:

```
import promiseFinally from 'promise.prototype.finally'
```

**Comment by ljharb** [comment]
@jonashaag is there any chance you have a codesandbox or jsfiddle link that can repro this? That would also help show which version of core-js is the problem (v2, or v3, etc).

Closing pending a repro.
