### ISSUE TITLE
shim() not shimming on karma/phantomJS

### ISSUE THREAD

**Issue by burabure** [es-shims/Promise.prototype.finally#6]
For some weird reason the shim() isn't able to shim the global Promise on karma with the phantomJS driver (the main app works fine, and the jasmine client version of the specs work fine on other browsers).

When debugging I see the shim hitting define-property here:
```js
if (supportsDescriptors) {
 // it actually fires this
  Object.defineProperty(object, name, {
    configurable: true,
    enumerable: false,
    value: value,
    writable: true
  });
} else { ... }
```
but then
```js
require('promise.prototype.finally').shim()
console.log(Promise.prototype.finally) // logs undefined
``` 

Now if I pass the Promise object to the shim and change the library function signature accordingly it works
```js
// shim.js
...
module.exports = function shimPromiseFinally(obj) {
	obj = obj || Promise;
	requirePromise();

	var polyfill = getPolyfill();
	define(obj.prototype, { 'finally': polyfill }, {
		'finally': function testFinally() {
			return obj.prototype['finally'] !== polyfill;
		}
	});
	return polyfill;
};
...


// karma.entry.js
require('promise.prototype.finally').shim(Promise)
console.log(Promise.prototype.finally) // logs the polyfill, it works!
```

I can submit a PR if you think this is something you want to add (I've seen other shimming libs do this too, perhaps this is a common issue)

-----
PS: for anyone wondering this is my quick fix for now:
```js
const finallyPolyfill = require('promise.prototype.finally').shim()

// Make sure we're shimming promise.finally.
// (auto .shim() doesn't work in karma for some reason)
if (!Promise.prototype.finally) { Promise.prototype.finally = finallyPolyfill }
```

**Comment by ljharb** [comment]
Hmm, that's definitely weird and worth looking into.

Since it's definitely calling `define`, and definitely hitting the `Object.defineProperty` branch - can you add a console.log to the shim function, on the first line, with `Promise`, `obj`, and `Promise.prototype`, and let me know what shows up?

**Comment by burabure** [comment]
```js
// karma.entry.js
require('promise.prototype.finally').shim(Promise)
...

// shim.js
module.exports = function shimPromiseFinally(obj) {
	obj = obj || Promise;

	console.log(obj, Promise, Promise.prototype) // logs: function Promise(executor) { ... }, function Promise() { ... }, Promise{}
	console.log(obj === Promise) // logs: false

	requirePromise();

	var polyfill = getPolyfill();
	define(obj.prototype, { 'finally': polyfill }, {
		'finally': function testFinally() {
			return obj.prototype['finally'] !== polyfill;
		}
	});
	return polyfill;
};
```

So the Promise at the karma entry is the global one for the specs, but the global one that the shim sees isn't the same.

**Comment by ljharb** [comment]
What's interesting there is neither of the `Promise` objects you have there are native code - do you have any other shims or polyfills running?

**Comment by burabure** [comment]
I'm using `babel-polyfill`

**Comment by ljharb** [comment]
@burabure ah ok - that's core-js. In what order are you including those things? `babel-polyfill` (just like `es6-shim`, if you were using that) needs to be imported before all other non-shim code; and `promise.prototype.finally` should be imported (to cache `Promise`) *after* `Promise` might be polyfilled, but ideally before other non-shim code.

**Comment by burabure** [comment]
@ljharb I tried changing the require order, it failed the same way. I believe it's an issue of different environments.

**Comment by ljharb** [comment]
I guess I'm not sure why karma and phantom would work differently - 100% of the code under test should be running in the same environment.

**Comment by burabure** [comment]
@ljharb I'm mostly speculating the details here but I know that the karma runner do control many drivers at the same time by sending messages to each one separately, so it would make sense that the runner's global environment will differ from the driver's.

**Comment by ljharb** [comment]
However, if that's the case, then `require` shouldn't be cached across environments.

**Comment by burabure** [comment]
@ljharb I think it might be the case because i'm using webpack with cacheing to (re)build the modules on karma.

**Comment by ljharb** [comment]
Unfortunately I wouldn't; that would allow people to try to shim `{}` for example.

**Comment by burabure** [comment]
I respect that, but out of curiosity could you explain a case where that could happen inadvertently or the reasoning behind it?.

**Comment by ljharb** [comment]
It's not that it's happen inadvertently. More that it expands the API and makes more parts of the implementation of the shim function observable.

I do want to fix this somehow; but it's starting to seem like a karma bug.

**Comment by ljharb** [comment]
Closing pending a repro.
